Repository hpi-sam/digital-fuesim-manv, pull requests merged in 2023-04, with the labels that each got.

#855 Fix GHSA-776f-qx25-q3cc
  backend/package-lock.json
Labels: dependencies

#853 Refactoring/resolve circular dependencies
  .eslint/typescript.eslintrc.cjs
  frontend/src/app/state/application/selectors/shared.selectors.ts
  shared/src/data/default-state/patient-templates.ts
  shared/src/export-import/file-format/state-export.ts
  shared/src/models/exercise-configuration.ts
  shared/src/models/simulated-region.ts
  shared/src/models/utils/spatial-tree.ts
  shared/src/simulation/activities/reassign-treatments.ts
  shared/src/simulation/behaviors/treat-patients.ts
  shared/src/store/action-reducers/transfer.ts
  shared/src/store/action-reducers/utils/calculate-treatments.ts
Labels: meta, refactoring

#899 Release v0.4.1
  CHANGELOG.md
  backend/package-lock.json
  backend/package.json
  backend/src/database/migrate-in-database.ts
  benchmark/package-lock.json
  benchmark/package.json
  docs/swagger.yml
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
  shared/package-lock.json
  shared/package.json
  shared/src/models/radiogram/radiogram-helpers-mutable.ts
Labels: bug, backend

#898 Enable source maps for backend
  backend/tsconfig.json
Labels: bug, dev-setup
