Repository hpi-sam/digital-fuesim-manv, pull requests merged in 2023-01, with the labels that each got.

#592 Update packages to mitigate GHSA-9c47-m6qq-7p4h
  backend/package-lock.json
  frontend/package-lock.json
  package-lock.json
  shared/package-lock.json
Labels: dependencies

#595 Update dependencies
  backend/package-lock.json
  backend/package.json
  benchmark/package-lock.json
  benchmark/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/shared/validation/custom-validation-errors.ts
  package-lock.json
  package.json
  shared/package-lock.json
  shared/package.json
  shared/src/models/utils/patient-status-code.ts
  shared/src/store/action-reducers/action-reducers.ts
Labels: dependencies

#606 Ignore vs code config files
  .gitignore
  .vscode/launch.json.example
  .vscode/settings.json.example
  .vscode/tasks.json.example
  README.md
Labels: dev-setup

#604 Refactor viewport-modify to resize-rectangle-interaction
  frontend/src/app/pages/exercises/exercise/shared/exercise-map/feature-managers/element-feature-manager.ts
  frontend/src/app/pages/exercises/exercise/shared/exercise-map/feature-managers/simulated-region-feature-manager.ts
  frontend/src/app/pages/exercises/exercise/shared/exercise-map/feature-managers/viewport-feature-manager.ts
  frontend/src/app/pages/exercises/exercise/shared/exercise-map/utility/modify-helper.ts
  frontend/src/app/pages/exercises/exercise/shared/exercise-map/utility/ol-map-manager.ts
  frontend/src/app/pages/exercises/exercise/shared/exercise-map/utility/rectangle-modify.ts
  frontend/src/app/pages/exercises/exercise/shared/exercise-map/utility/resize-rectangle-interaction.ts
Labels: frontend
